#!/usr/bin/env python3
from pathlib import Path
import re

p = Path("android/app/src/main/java/com/streamflixvip/app/ui/player/PlayerScreen.kt")
t = p.read_text()
assert "suspend fun applyOnlineSubtitle" in t

if "import androidx.media3.datasource.DefaultDataSource" not in t:
    t = t.replace(
        "import androidx.media3.datasource.DefaultHttpDataSource\n",
        "import androidx.media3.datasource.DefaultDataSource\nimport androidx.media3.datasource.DefaultHttpDataSource\n",
    )

m = re.search(r"    suspend fun applyOnlineSubtitle\(item: SubtitleSearchItem\) \{.*?\n    \}\n\n    fun selectAudio", t, re.S)
if not m:
    m = re.search(r"    suspend fun applyOnlineSubtitle\(item: SubtitleSearchItem\) \{.*?\n    \}\n", t, re.S)
    if not m:
        raise SystemExit("applyOnlineSubtitle not found")
    end = m.end()
else:
    end = m.end() - len("    fun selectAudio")

lines = []
lines.append("    suspend fun applyOnlineSubtitle(item: SubtitleSearchItem) {")
lines.append("        val fileId = item.file_id ?: return")
lines.append("        onlineSubtitlesLoading = true")
lines.append("        onlineSubtitlesError = null")
lines.append("        try {")
lines.append('            val seasonArg = if (mediaType == "tv" && currentSeason > 0) currentSeason else null')
lines.append('            val episodeArg = if (mediaType == "tv" && currentEpisode > 0) currentEpisode else null')
lines.append("            val resp = NetworkModule.subtitlesApi.download(")
lines.append("                fileId = fileId,")
lines.append("                tmdbId = tmdbId,")
lines.append('                mediaType = if (mediaType == "tv") "tv" else "movie",')
lines.append("                season = seasonArg,")
lines.append("                episode = episodeArg,")
lines.append("            )")
lines.append("            val content = resp.content")
lines.append("            if (content.isNullOrBlank()) {")
lines.append('                onlineSubtitlesError = resp.error ?: "Legenda vazia"')
lines.append("                return")
lines.append("            }")
lines.append(r'            var vtt = content.replace("\r\n", "\n").replace("\r", "\n")')
lines.append('            if (!vtt.trimStart().startsWith("WEBVTT", ignoreCase = true)) {')
lines.append(r'                vtt = "WEBVTT\n\n" + vtt.replace(",", ".")')
lines.append("            }")
lines.append(r'            val file = File(context.cacheDir, "os_${tmdbId}_${currentSeason}_${currentEpisode}.vtt")')
lines.append("            file.writeText(vtt, Charsets.UTF_8)")
lines.append("")
lines.append("            val pos = exoPlayer.currentPosition.coerceAtLeast(0L)")
lines.append("            val wasPlaying = exoPlayer.playWhenReady")
lines.append("            val durationUs = exoPlayer.duration.takeIf { it > 0L } ?: (5L * 60 * 60 * 1_000_000L)")
lines.append("")
lines.append("            val subConfig = MediaItem.SubtitleConfiguration.Builder(Uri.fromFile(file))")
lines.append("                .setMimeType(MimeTypes.TEXT_VTT)")
lines.append('                .setLanguage("pt")')
lines.append('                .setLabel(item.release ?: "Online PT-BR")')
lines.append("                .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)")
lines.append("                .build()")
lines.append("")
lines.append("            val dsFactory = DefaultHttpDataSource.Factory()")
lines.append('                .setUserAgent("VLC/3.0.4 LibVLC/3.0.4")')
lines.append("                .setDefaultRequestProperties(")
lines.append("                    mapOf(")
lines.append('                        "Referer" to activeUrl,')
lines.append('                        "Connection" to "keep-alive",')
lines.append('                        "Icy-MetaData" to "1",')
lines.append("                    ),")
lines.append("                )")
lines.append("            val localFactory = DefaultDataSource.Factory(context, dsFactory)")
lines.append("            val extFactory = DefaultExtractorsFactory().setConstantBitrateSeekingEnabled(true)")
lines.append("            val videoItem = MediaItem.fromUri(activeUrl)")
lines.append("            val videoSource = if (isLikelyHls(activeUrl)) {")
lines.append("                HlsMediaSource.Factory(dsFactory).createMediaSource(videoItem)")
lines.append("            } else {")
lines.append("                ProgressiveMediaSource.Factory(dsFactory, extFactory).createMediaSource(videoItem)")
lines.append("            }")
lines.append("            val subtitleSource = SingleSampleMediaSource.Factory(localFactory)")
lines.append("                .createMediaSource(subConfig, durationUs)")
lines.append("            val merged = MergingMediaSource(videoSource, subtitleSource)")
lines.append("")
lines.append("            trackSelector.parameters = trackSelector.parameters.buildUpon()")
lines.append("                .clearOverridesOfType(C.TRACK_TYPE_TEXT)")
lines.append("                .setTrackTypeDisabled(C.TRACK_TYPE_TEXT, false)")
lines.append('                .setPreferredTextLanguage("pt")')
lines.append("                .setSelectUndeterminedTextLanguage(true)")
lines.append("                .build()")
lines.append("")
lines.append("            exoPlayer.setMediaSource(merged)")
lines.append("            exoPlayer.prepare()")
lines.append("            exoPlayer.seekTo(pos)")
lines.append("            exoPlayer.playWhenReady = wasPlaying")
lines.append("")
lines.append("            exoPlayer.addListener(object : Player.Listener {")
lines.append("                override fun onTracksChanged(tracks: Tracks) {")
lines.append("                    val groups = tracks.groups")
lines.append("                    for (gi in 0 until groups.size) {")
lines.append("                        val group = groups[gi]")
lines.append("                        if (group.type != C.TRACK_TYPE_TEXT) continue")
lines.append("                        for (ti in 0 until group.length) {")
lines.append("                            if (!group.isTrackSupported(ti)) continue")
lines.append("                            trackSelector.parameters = trackSelector.parameters.buildUpon()")
lines.append("                                .setOverrideForType(TrackSelectionOverride(group.mediaTrackGroup, ti))")
lines.append("                                .setTrackTypeDisabled(C.TRACK_TYPE_TEXT, false)")
lines.append("                                .build()")
lines.append("                            exoPlayer.removeListener(this)")
lines.append("                            return")
lines.append("                        }")
lines.append("                    }")
lines.append("                }")
lines.append("            })")
lines.append("")
lines.append('            val short = (item.release ?: "PT-BR").let { if (it.length > 28) it.take(28) + "..." else it }')
lines.append('            selectedSubtitleLabel = "Online: $short"')
lines.append("            onlineSubtitleApplied = true")
lines.append("            settingsPanel = SettingsPanel.MAIN")
lines.append("        } catch (e: Exception) {")
lines.append('            onlineSubtitlesError = e.message ?: "Falha ao baixar legenda"')
lines.append("        } finally {")
lines.append("            onlineSubtitlesLoading = false")
lines.append("        }")
lines.append("    }")
lines.append("")
new_fn = "\n".join(lines) + "\n"
t = t[:m.start()] + new_fn + t[end:]
p.write_text(t)
print("patched", len(t))
assert "DefaultDataSource.Factory" in t
assert "localFactory" in t
assert "durationUs" in t
print("ok")
